
networks:
  hwci:
    driver: bridge

services:   
  postgresql:
    hostname: postgresql
    image: postgres:16
    container_name: postgres-16
    environment:
      POSTGRES_HOST: "localhost"
      POSTGRES_DB: "dockerdb"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DBPARAMS: "--lc-collate=C --template=template0 --lc-ctype=C" 
    volumes:
      - ~hwci/infra/postgresql/initdb:/docker-entrypoint-initdb.d
      - ~hwci/storage/postgresql/data:/var/lib/postgresql/data
      - ~hwci/storage/postgresql/log:/var/log/postgresql
    ports:
      - "127.0.0.1:6432:5432"
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d dockerdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    logging:
      options:
        max-size: 10m
    networks:
      - hwci
      
  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer
    ports:
      - 8383:8080
    logging:
      options:
        max-size: 10m
    networks:
      - hwci
 
